- test/unit/activity.spec.js
- test/unit/testServer.js
Abstracts hapi test server creation out to separate file so it can be shared between test files
> REP-334 Updates to test structure

- .travis.yml
- api/organization.js
- db/repositories/organizationsRepository.js
- package.json
- test/integration/organizations.spec.js
- test/integration/sharedDatabase.js
- test/integration/sharedLogger.js
- test/unit/activity.spec.js
- test/unit/mockUoW.js
- test/unit/organizations.spec.js
- test/unit/testServer.js
Will need a test db started for integration tests to be successful.
> REP-305 Add tests for organizations api and repository

- config.js
- index.js
- package.json
- yarn.lock
Can test by running: `redis-cli monitor` on the redis image. As requests come in, you'll see key/values being stored. Test the rate limiting by repeating the same request over and over and eventually getting the rate limited 429 status.
> REP-294 Use redis catbox for caching/rate limiting.

- api/auth.js
- test/unit/auth.spec.js
- test/unit/mockHelper.js
- test/unit/mockUoW.js
Needs to be rebased once REP-307 is merged as 304 is branched off of 307.
> REP-304 - Auth unit testing

- db/repositories/permissionsRepository.js
- test/integration/permissions.spec.js
- test/unit/mockUoW.js
- test/unit/permissions.spec.js
Rebased off of REP-307. Do not merge before 307
> REP-306 - Add unit tests for permissions API

- api/users.js
- test/unit/users.spec.js
REP-366 Added a new endpoint to check if a user exists or not based on the primary email address
REP-366 Added unit testing for checking users by email address
> [REP-366 -> master] API - Check for existing user based on email

- config.js
id:1134 Updated the rejectUnauthorizedTLS config to allow for sending emails
> [ task-1134 -> master ] Change TLS config in mail

- api/organization.js
task-1131 updated the create organization endpoint to also take organization address info
> [us-317 -> master] API - Survey Details

- api/applications.js
- extensions.js
- helpers/getApplicationList.js
- index.js
- package.json
- test/unit/applications.spec.js
- test/unit/testServer.js
- yarn.lock
https://sevenhillstechnology.tpondemand.com/entity/1724-application-token-auth-blocking-everything-in
> Bug-1724 Fix issues with application token authentication blocking all requests

- api/auth.js
- api/services/emailService.js
- api/users.js
- extensions.js
- index.js
- package.json
- test/unit/activity.spec.js
- test/unit/applications.spec.js
- test/unit/auth.spec.js
- test/unit/organizations.spec.js
- test/unit/permissions.spec.js
- test/unit/roles.spec.js
- test/unit/testServer.js
- test/unit/users.spec.js
- yarn.lock
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/328-api-authenticate-application-token)
Addressed in this PR:
1. When sending a verification email, check for application token for custom email body (`id:329`)
2. When sending an unauthenticated request, check for a valid application token (`id:328`)
3. Updating platform api to use hapijs-starter v5.1.0 (necessary for addition of application token cors header)
> [ us-324 -> dev ] Managed IT Post Survey Updates

- api/applications.js
- api/organization.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/2753-api-remove-user-organization-creation-logic)
Adding jwt to application auth routes, updating joi suiteNumber validation to allow empty strings, fixing a null check to allow `undefined` to act the same as `null` after checking for existence of an organization.
Related PRs: https://github.com/reperio/managed-it-api/pull/26
> [ us-2647 -> dev ] Auth Strategies updates

- api/applications.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/2754-api-add-userid-and-organizationid-to)
Making `/userSignup` return the new userId and organizationIds
Related PR: https://github.com/reperio/managed-it-api/pull/29
> [ us-2754 -> dev ] userSignup returns userId and organizationIds

- api/applications.js
- api/users.js
- db/repositories/organizationsRepository.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/2802-on-new-user-creation-create-a)
Update to POST `/application/*/userSignup` to create a personal organization (along with the survey organizations)
Update to POST `/users` to change the default personal organization name to be First + Last name instead of Primary Email
> [ us-2802 -> dev ] Create Personal Organization on User Creation

- api/services/authService.js
https://sevenhillstechnology.tpondemand.com/entity/2651-return-orgids-in-jwt
> US-2651 Return organization ids in JWT

- api/organization.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/2851-filter-personal-organizations-from-authenticated-survey)
Removing route check for ViewOrganizations permission
Related PR: https://github.com/reperio/managed-it-ui/pull/28
> [ us-2851 -> dev ] Removing route check for ViewOrganizations permission

- api/applications.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/2858-users-should-be-inserted-with-disabled)
Adding `disabled` and `delete` flags as explicitly false for users signed up through a survey.
> [ us-2858 -> dev ] users are not deleted nor disabled after survey signup

- api/applications.js
- db/repositories/applicationsRepository.js
- db/seeds/3-permissions.js
- db/seeds/6-rolePermissions.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/2895-add-organization-search-to-applications)
> [ us-2895 -> dev ] Add Organization Search to Applications

- api/organization.js
- api/users.js
- db/repositories/organizationsRepository.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/2278)
> [ feature-2278 -> dev ] Stripe Payment related updates for MITS

- api/applications.js
- api/services/emailService.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/3472-update-user-signup-for-updatepassword)
Updating user sign up process to use verfication email service and send `next` link based on application
> [ us-3472 -> dev ] Verification email passes next link through reset url

- api/organization.js
- api/services/emailService.js
- config.js
route and helper functions to send new customer notification email
https://sevenhillstechnology.tpondemand.com/RestUI/Board.aspx#page=board/5165084486614971430&appConfig=eyJhY2lkIjoiMTExMTJBRUVDRUU0RUUyMDExMDRFRDQ4NkM4QzJFOTQiLCJhcHBDb250ZXh0Ijp7InByb2plY3RDb250ZXh0Ijp7Im5vIjpmYWxzZX0sInRlYW1Db250ZXh0Ijp7Im5vIjp0cnVlfX19&boardPopup=feature/3168/silent
> us-3534 -> dev

- db/models/user.js
- db/repositories/usersRepository.js
* id:3487 changed reference from userOrganization table to the userRoles.organization
* id:3491 fixed reference to the organzation to correctly go through roles
> [ us-3484 -> dev ] user's grid giving a 500

- docker-compose.yml
https://sevenhillstechnology.tpondemand.com/entity/3381-link-managed-it-to-redis
> US-3381 Allow reperio core redis to be accessed by other reperio services

- api/organization.js
- api/permissions.js
- api/roles.js
- api/users.js
- db/repositories/organizationsRepository.js
- db/repositories/permissionsRepository.js
- db/repositories/rolesRepository.js
- db/repositories/usersRepository.js
- helpers/queryHelper.js
This covers pagination, sorting, and filtering: us-3850, us-3851, and us-3852.
> us-3852 - Add Server Side Pagination to Tables in Managed IT UI

- api/auth.js
- api/users.js
[Target Process](https://sevenhillstechnology.tpondemand.com/entity/3335-emails-are-case-sensitive)
Updating core api to set email to lower case in all routes.
> bug-3335 emails are case sensitive

- api/auth.js
- api/services/httpResponseService.js
- api/users.js
> dev -> master

- api/users.js
[Azure DevOps](https://dev.azure.com/sevenhillstechnology/Reperio/_workitems/edit/990 )
> u-990 if user has no password on invite, send new user email
